NetRomSummerCampApp/Controllers/EditAnnouncementController.cs
using NetRomSummerCampApp.Models;
using NetRomSummerCampApp.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace NetRomSummerCampApp.Controllers
{
    public class EditAnnouncementController : Controller
    {
   
       [HttpGet]
        public ActionResult Close(int id)
        {
            return View();
        }
        [HttpPost]
        public async System.Threading.Tasks.Task<ActionResult> Close(AnnouncementAuthViewModel vm)
        {
            string url = "http://api.summercamp.stage02.netromsoftware.ro/api/announcements/CloseAnnouncement?announcementId=" + vm.Id;
            using (HttpClient httpClient = new HttpClient())
            {
                AnnouncementAuthDTO entity = new AnnouncementAuthDTO();
                entity.Email = vm.Email;


                JavaScriptSerializer serialize = new JavaScriptSerializer();
                serialize.Serialize(entity);
                var json = new JavaScriptSerializer().Serialize(entity);

                StringContent content = new StringContent(json, Encoding.UTF8, "application/json");

                HttpClient client = new HttpClient();

                HttpResponseMessage response = await client.PostAsync(url, content);
                return RedirectToAction("Index","Home",null);
            }
            return View("Error");
        }



        [HttpGet]
        public ActionResult Extend(int id)
        {
            ViewBag.Id = id;
            return View();
        }

        [HttpPost]
        public async System.Threading.Tasks.Task<ActionResult> Extend(AnnouncementAuthViewModel vm)
        {
            string url = "http://api.summercamp.stage02.netromsoftware.ro/api/announcements/ExtendAnnouncement?announcementId=" + vm.Id;

            
            using (HttpClient httpClient = new HttpClient())
            {
                AnnouncementAuthDTO entity = new AnnouncementAuthDTO();
                entity.Email = vm.Email;


                JavaScriptSerializer serialize = new JavaScriptSerializer();
                serialize.Serialize(entity);
                var json = new JavaScriptSerializer().Serialize(entity);

                StringContent content = new StringContent(json, Encoding.UTF8, "application/json");

                HttpClient client = new HttpClient();

                HttpResponseMessage response = await client.PostAsync(url, content);
                return RedirectToAction("Index","Home",null);
            }
            return View("Error");
        }
    }
}

NetRomSummerCampApp/Views/EditAnnouncement/Close.cshtml
@model NetRomSummerCampApp.ViewModel.AnnouncementAuthViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (@Html.BeginForm("Close", "EditAnnouncement", FormMethod.Post))
{
    <div class="form-group">
        <input type="hidden" id="Id" value="@(ViewBag.Id)"
               @*@Html.HiddenFor(x => x.Id)*@
               @Html.LabelFor(x => x.Email)
               @Html.TextBoxFor(x => x.Email)
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
}

NetRomSummerCampApp/Views/EditAnnouncement/Extend.cshtml
@model NetRomSummerCampApp.ViewModel.AnnouncementAuthViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container" align="center" style="margin:20% 0">
    @using (@Html.BeginForm("Extend", "EditAnnouncement", FormMethod.Post))
    {
        <div class="form-group">
            <input type="hidden" id="Id" value="@(ViewBag.Id)"
                   @*@Html.HiddenFor(x => x.Id)*@
                   @Html.LabelFor(x => x.Email, new { @class = "form-control" })
                   @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
    }
</div>